name: Strip HTML Wrapper from help.html

on:
  push:
    paths:
      - help.html

jobs:
  strip-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with full access
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Strip <html>/<body> tags from help.html
        run: |
          sed -n '/<body/,/<\/body>/p' help.html \
          | sed '1s/.*<body[^>]*>//' \
          | sed '$s/<\/body>.*//' > help_stripped.html

      - name: Commit and push help_stripped.html
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add help_stripped.html
          git commit -m "Auto-update stripped HTML" || echo "No changes to commit"
          
          # Set remote to use PAT for authentication
          git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}.git
          git push origin HEAD:main
